### PR TITLE
Code Cleanup

### PR DESCRIPTION
**Pull request by mattvella07**
Cleaned up the code based on messages from linter, and updated eslintrc file to comment out rules (no-dupe-class-members, prefer-arrow-callback, prefer-template) that are not supported by this version of the linter.  The version of the linter we use is based on eslint 1.1, and the previously mentioned rules are supported by eslint 1.2.

### CODE REVIEW

**Comment by zaverichintan** [comment]
Will there be any major changes the to the settings?

**Comment by mattvella07** [comment]
Nope, just removed the settings that our version of the linter doesn't support so you will see less warnings when running meteor command.

**Comment by zaverichintan** [comment]
Are we planning to upgrade our linter?  If yes, then we might have to chahe the settings

**Comment by mattvella07** [comment]
We are using the latest version of the linter meteor package but it is based on a previous version of the linter NPM package.  So we can't upgrade right now.

**Comment by pmuens** [comment]
Great! Thanks as always!

**Pull request merged**
