### PR TITLE
Refers to issue #58 Search Users 

### PR DESCRIPTION
**Pull request by mohsalsaleem**
A search page with search functionality which can search for users with their <username>. This page can replace the browse users page.

### CODE REVIEW

**Comment by nchenbang** [comment]
This `matteodem/meteor-easy-search` package might be a great solution for all pagination and searching functionalities in this project but one thing I think it is bad is that it has heavy dependency on `peerlibrary/meteor-blaze-components`.

**Comment by pmuens** [comment]
Are there any better approaches available? What about a MongoDB full text search like it's implemented for searching for posts?

**Comment by mohsalsaleem** [comment]
How about search source by Meteor hacks ?

**Comment by nchenbang** [comment]
If I'm not mistaken, search source is using MongoDB regular expression queries for text search which is not an ideal solution in terms of performance.

About the easy search, you can actually use MongoDB full text search in it by selecting the MongoTextIndex engine. I think easy search is more of a full solution that covers not only the text search, but also functionalities like blaze components, paginations and autosuggest. Well, all these stuffs can be done manually even without easy search so I guess the choice depends on whether you want to rely on a third party package or do all the piping yourself.

**Comment by pmuens** [comment]
IMHO I think the less third party packages, the better. But I have no experience with easysearch so far. Perhaps it's a good solution we can use everywhere.

**Comment by nchenbang** [comment]
I think I'm agree with you here, it's bad to have too much dependency on third party packages.

**Comment by mohsalsaleem** [comment]
Yeah.. I agree. I'll try implementing MongoDB full text search.

Mohamed Saleem. H

**Comment by pmuens** [comment]
Great! I've implemented something similar with posts. Here's the commit @mohsalsaleem 77eb4cabfd0b1b35da22cbe01620b01d2e96ce4a

**Pull request closed without merging**
