### PR TITLE
Cleaned Up Code

### PR DESCRIPTION
**Pull request by mattvella07**
Removed/added spacing to remove warnings from linter, as mentioned in issue #104.

### CODE REVIEW

**Comment by pmuens** [comment]
Great! Thanks man!

**Comment by zaverichintan** [comment]
Excellent, what settings do we have to do while configuring code editor?

**Comment by pmuens** [comment]
Well I think it would be best to stick to [this](https://github.com/GravityProject/gravity/blob/master/CONTRIBUTING.md) and the [Meteor style guide](https://github.com/meteor/meteor/wiki/Meteor-Style-Guide).

**Comment by zaverichintan** [comment]
2 space indents (setq js-indent-level 2)

spaces, not literal tabs (setq-default indent-tabs-mode nil)

no trailing whitespace (setq-default show-trailing-whitespace t)

We might add this in contributoring readme

**Comment by pmuens** [comment]
Good idea :+1:

**Pull request merged**
