### PR TITLE
#90, Dropdown with availabe usernames when composing a message

### PR DESCRIPTION
**Pull request by mattvella07**
In the 'To' field a dropdown of available usernames is displayed as you type (not including your own).  I used the mizzao:autocomplete package for this and it didn't really customize it, so let me know what you think.

### CODE REVIEW

**Comment by pmuens** [comment]
@mattvella07 You've done it again! Awesome job! :fireworks:

**Comment by pmuens** [comment]
BTW. What's you username on Gravity?

**Comment by mattvella07** [comment]
mattvella07, what's yours?

**Comment by pmuens** [comment]
pmuens

**Pull request merged**
