### PR TITLE
Closes #63 - "No elements to display" message is shown whenever the subscription is not ready.

### LINKED ISSUE #63: "There are no matching posts to display" message is being displayed whenever the subscription is not ready.

### PR DESCRIPTION
**Pull request by nchenbang**

### CODE REVIEW

**Comment by pmuens** [comment]
Nice addition! Thanks! Will revisit and merge it ASAP. :boom:

**Comment by pmuens** [comment]
This is really cool! Could you add the check for the posts on the users profile as well?

https://github.com/GravityProject/gravity/blob/master/client/views/users/profile.js

Thanks!

**Comment by nchenbang** [comment]
Global helper `simpleFormat` is causing errors in browser console, not sure if you've already noticed about this. And I think we should come up with a way to deal with the flickering issues when navigate between templates, maybe subscription manager is the answer.

**Comment by pmuens** [comment]
Thanks you!
I'll take a look into the simpleFormat console output. Might have smth. todo with optional user biography.

**Pull request merged**
