### PR TITLE
Adding messaging, #6 1:1 messages

### PR DESCRIPTION
**Pull request by mattvella07**
This ties to issue #6 1:1 messages and adds messaging functionality between two users.

### CODE REVIEW

**Comment by pmuens** [comment]
Thank you! :+1:  I'll merge it ASAP.

**Comment by mattvella07** [comment]
#85 Confirmation Popups is included in this PR

**Comment by pmuens** [comment]
Great :+1: Thanks!

**Comment by pmuens** [comment]
Pretty cool stuff! Thank you very much! Really like the way you code! :+1:

**Pull request merged**
