### PR TITLE
Markdown support in posts

### PR DESCRIPTION
**Pull request by zaverichintan**
This helps to load markdown in the post. The posts with markdown will be displayed in proper format and non marked down will be as it is .

Signed-off-by: Chintan Zaveri <zaveri_chintan@rediff.com>

### CODE REVIEW

**Comment by zaverichintan** [comment]
image

**Comment by pmuens** [comment]
Great! This is really cool! Thanks @zaverichintan

**Comment by pmuens** [comment]
Just one modification. Could you remove the not related packages so that the commit is self contained and has only the relevant stuff in it. Thanks!

**Comment by zaverichintan** [comment]
Done. Thanks for pointing out .

**Comment by zaverichintan** [comment]
Also added highlight js to highlight code in markdown section

**Comment by pmuens** [comment]
Thank you!

**Pull request merged**
