### PR TITLE
Issue #27 adding user presence

### PR DESCRIPTION
**Pull request by anastalaz**
Added fa-user icon next to username which turns green when user is online using the mizzao:user-status package.

### CODE REVIEW

**Comment by nchenbang** [comment]
`mizzao:user-status` won't work once your application scales to multiple server since the user presence status is held in an in-memory collection. You can read more about it [here](https://forums.meteor.com/t/package-for-monitoring-users-online-status-presence/13687).

**Comment by anastalaz** [comment]
I see, thanks for the info. Someone mentioned [konecty:meteor-user-presence](https://github.com/Konecty/meteor-user-presence) could handle multiple instances. Any thoughts?

**Comment by pmuens** [comment]
Thanks for the PR! I will look into it. Although I have no further information about the scalability. But we should definitely discuss this.

**Comment by pmuens** [comment]
I'll merge this and opened up another issue for the performance discussion. We can change it later on when there's more traffic on the website and we run into problems.

**Pull request merged**
